Repository MIT-Emerging-Talent/2024-group-02-cdsp, pull requests merged in 2024-02, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation

#11 - scraps laid emploees list
  .gitignore
  src/emploees.py
  src/parcer.py
Labels: enhancement, help wanted

#17 Readme update
  README.md
  data_sources/cleaned_tech_layoffs_data.csv
Labels: documentation, enhancement

#21 Update README.md
  README.md
Labels: documentation

#26 Created_Milestones_folders
  Milestone/Milestone1/Readme.md
  Milestone/Milestone2/Data Collection.md
  Milestone/Milestone2/Readme.md
  Milestone/Milestone3/Data analysis.md
  Milestone/Readme.md
Labels: documentation
